# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'MotionDesignBook' do

pod 'JNWSpringAnimation'
pod 'pop'

end

target 'MotionDesignBookTests' do

end

